Homework 11: Vladislav Medvedev
dmitrysadovskii/tms05_onl pull request #101
Opened 2022-01-31 19:03 UTC by vladm201098

2022-02-10 14:03 UTC, dmitrysadovskii requested changes

2022-02-10 14:03 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_11/func.py
> +class Methods(ABC):
Давай более осмысленное название классу. Это ведь методы калькулятора, так и назови класс так тогда)

2022-02-10 14:03 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_11/main.py
> +import func
Ты же можешь импортировать сразу класс
from func import Methods

2022-02-10 14:03 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_11/main.py
> +def validate(a, b):
Вынеси в класс калькулятор и поменть как статический метод

2022-02-10 14:03 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_11/main.py
> +    if not isinstance(a, int) or not isinstance(b, int):
Данный метод можно заменить одной строчкой.
assert all(isinstance(number, int) for number in (x, y)), "x or y must be int"

2022-02-10 14:03 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_11/main.py
> +        val = validate(a, b)
вместо данной строчки можно использовать asser, тогда если переменные будет не верные, то тест упадет, а если нет, то продолжит дальше и это позволит убрать не ныжй if

2022-02-10 14:03 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_11/main.py
> +            if b != 0:
Тут молодец, что не стал использовать try/except)

2022-02-23 21:15 UTC, vladm201098 commented on vladslav_medvedev/hm_11/main.py
> +import func
Готово!

2022-02-23 21:15 UTC, vladm201098 commented on vladslav_medvedev/hm_11/main.py
> +def validate(a, b):
Готово!

2022-02-23 21:15 UTC, vladm201098 commented on vladslav_medvedev/hm_11/main.py
> +        val = validate(a, b)
Готово!

2022-02-23 21:15 UTC, vladm201098 commented on vladslav_medvedev/hm_11/main.py
> +            if b != 0:
Thanks)

2022-03-11 08:20 UTC, dmitrysadovskii commented
Все хорошо)

2022-03-11 08:20 UTC, merged