Homework11: Veronika Ivashko
dmitrysadovskii/tms05_onl pull request #102
Opened 2022-01-31 19:57 UTC by nik-ar

added files for eleventh homework

2022-02-10 14:58 UTC, dmitrysadovskii requested changes

2022-02-10 14:58 UTC, dmitrysadovskii commented on veronika_ivashko/hw_11/func.py
> +    @staticmethod
Зачем данные методы сделала статическими?

2022-02-10 14:58 UTC, dmitrysadovskii commented on veronika_ivashko/hw_11/func.py
> +class AllMethods(ABC):
Давай более осмысленное название классу. Это ведь методы калькулятора, так и назови класс так тогда)

2022-02-10 14:58 UTC, dmitrysadovskii commented on veronika_ivashko/hw_11/func.py
> +        if num.isdigit():
Если сюда передать букву, то сработает else блок и программа упадет

2022-02-10 14:58 UTC, dmitrysadovskii commented on veronika_ivashko/hw_11/func.py
> +    @staticmethod
Почему данные метода класса являются статическими, если это непосредственно те операции, которые должен делать калькулятор?

2022-02-10 14:58 UTC, dmitrysadovskii commented on veronika_ivashko/hw_11/func.py
> +    operations = {
Если это константа, то пиши заглавными буквами

2022-02-10 14:58 UTC, dmitrysadovskii commented on veronika_ivashko/hw_11/func.py
> +        else:
Если if сработает, то вернется значение, если нет, то тогда будет принт и не важно есть конструкция else или нет, поэтому else можно убрать

2022-02-10 14:58 UTC, dmitrysadovskii commented on veronika_ivashko/hw_11/func.py
> +        :return: True if input is valid, None if not.
Почему у Тебя в позитивном случае возвращается True, а в негативном None. Логичнее было бы вернуть False, так как None значит "ничего/пусто" а не "не верно"

2022-02-10 14:58 UTC, dmitrysadovskii commented on veronika_ivashko/hw_11/func.py
> +        try:
is_valid_number = '1.69'.replace('.', '', 1).isdigit()
assert is_number, 'Please, enter only positive or negative numbers.'
Так можно упростить код избавив от ненужного перехватывания ошибки

либо можешь 
if is_valid_number:
   return True
return False

2022-02-12 10:10 UTC, nik-ar commented on veronika_ivashko/hw_11/func.py
> +        if num.isdigit():
в этом методе происходит только конвертация, на вход подается отвалидированное число, т.е. строка сюда не должна заходить, т.к. есть отдельный класс Validation, который должен проверить это сначала. были мысли валидировать внутри функций, но по сути это одни и те же валидации, поэтому они все в отдельном классе.

2022-02-12 10:15 UTC, nik-ar commented on veronika_ivashko/hw_11/func.py
> +        :return: True if input is valid, None if not.
цель была просто получить 'negative', чтобы при условиях можно было использовать аналогично True/False, и т.к. None это False, думала не дописывать return False, ок, fixed

2022-02-12 10:43 UTC, nik-ar commented on veronika_ivashko/hw_11/func.py
> +        try:
тут логика по сути проверить, является ли ввод числом в принципе, или буквами/символами, и выдать True/False - может ли это число дальше обрабатываться, и assert мне тут не очень нравится, потому что логики обработки выброшенных ошибок наверху, чтобы не обвалить программу у меня нет, а вот с replace + isdigit интересная идея, я все ломала голову, как быть с дробной частью, спасибо, fixed.

2022-02-12 10:50 UTC, nik-ar commented on veronika_ivashko/hw_11/func.py
> +    @staticmethod
идея была в том, что у самого класса как такового нет планировалось своих атрибутов и вызывать в мат.функциях я их не собиралась, т.е. они просто объединены под этим методом, ок, fixed.

2022-02-12 10:50 UTC, nik-ar commented on veronika_ivashko/hw_11/func.py
> +class AllMethods(ABC):
fixed.

2022-02-12 10:51 UTC, nik-ar commented on veronika_ivashko/hw_11/func.py
> +    @staticmethod
fixed.

2022-02-12 10:51 UTC, nik-ar commented on veronika_ivashko/hw_11/func.py
> +    operations = {
fixed.

2022-02-12 10:52 UTC, nik-ar commented on veronika_ivashko/hw_11/func.py
> +        else:
точно, спасибо, fixed.

2022-02-12 10:55 UTC, nik-ar commented on veronika_ivashko/hw_11/task_11.py
> +                    result = math_operation(calc, x, y)
в том числе изначально делала методы статическими, чтобы не было такой записи для функций (calculator, x, y), а просто были (x,y), но ок, теоритически они могли бы вызываться в каком-то параллельном калькуляторе (объекте) и мы тут просто явно говорим, через какой калькулятор исполнить

2022-02-18 06:01 UTC, merged