Homework11:Anastasiya Matysheva
dmitrysadovskii/tms05_onl pull request #104
Opened 2022-02-01 07:12 UTC by AnastasiyaMava

2022-02-10 15:02 UTC, dmitrysadovskii requested changes

2022-02-10 15:02 UTC, dmitrysadovskii commented on anastasiya_matysheva/hm_11/func.py
> +class Methods(ABC):
Давай более осмысленное название классу. Это ведь методы калькулятора, так и назови класс так тогда)

2022-02-10 15:02 UTC, dmitrysadovskii commented on anastasiya_matysheva/hm_11/main.py
> +    @staticmethod
Почему данные методу статические? Они же выполняют непосредственно действия, которые должен делать калькулятор

2022-02-10 15:02 UTC, dmitrysadovskii commented on anastasiya_matysheva/hm_11/main.py
> +        raise TypeError("Invalid data type")
Почему выше перехватываешь ValueError, а дальше рейзись TypeError?

2022-02-10 15:02 UTC, dmitrysadovskii commented on anastasiya_matysheva/hm_11/main.py
> +        except Exception as error:
Почему Ты делаешь try/ except если до этого проверяла значения в функции validation?

2022-03-15 13:09 UTC, AnastasiyaMava commented on anastasiya_matysheva/hm_11/main.py
> +    @staticmethod
Был мой косяк и мне PC предложил так. После исправления косяка все ок

2022-03-15 13:09 UTC, AnastasiyaMava commented on anastasiya_matysheva/hm_11/main.py
> +        raise TypeError("Invalid data type")
Я перехватыеваю исключения ValueError и генерирую в собственное TypeError с собственным описанием. Чтобы при возниконовении исключения отображался мой текст.

2022-03-15 13:10 UTC, AnastasiyaMava commented on anastasiya_matysheva/hm_11/main.py
> +        except Exception as error:
Чтобы перехватывать исключения и выводился мой текст при их возникновении

2022-03-16 11:39 UTC, merged