Homework3: Natallia Kodz
dmitrysadovskii/tms05_onl pull request #13
Opened 2021-12-26 12:27 UTC by kodznata

2021-12-26 17:07 UTC, dmitrysadovskii requested changes
Необходимо переделать задания 3_2 в соответствии с комментарием

2021-12-26 17:07 UTC, dmitrysadovskii commented on natallia_kodz/hm_3/task_3_2.py
> +print(f"{word}ing")
Нужно что бы программа сама подставляла ing окончания, а не руками.
a = "My name is Dzmitry"
---//---
Что-то делает код
---//---
print(a)
Выведет: "Mying nameing ising Dzmitrying"

2021-12-26 17:07 UTC, dmitrysadovskii commented on natallia_kodz/hm_3/task_3_4.py
> +print(a[1:-1])
В данном случае если будет 2 пробела вначале или в конце, то не сработает

2021-12-26 17:07 UTC, dmitrysadovskii commented on natallia_kodz/hm_3/task_3_4.py
> +print(a.strip())
Это ок

2021-12-27 20:23 UTC, kodznata commented on natallia_kodz/hm_3/task_3_4.py
> +print(a[1:-1])
Поняла

2021-12-27 20:24 UTC, kodznata commented on natallia_kodz/hm_3/task_3_2.py
> +print(f"{word}ing")
Переделала

2021-12-28 14:16 UTC, dmitrysadovskii commented on natallia_kodz/hm_3/task_3_4.py
> +print(a[1:-1])
Удали это решение и тогда смержу домашку.

2021-12-28 14:29 UTC, kodznata commented on natallia_kodz/hm_3/task_3_4.py
> +print(a[1:-1])
Удалила

2021-12-28 14:57 UTC, merged