Homework3: Veronika Ivashko
dmitrysadovskii/tms05_onl pull request #16
Opened 2021-12-26 15:20 UTC by nik-ar

added files for third hw

2021-12-26 17:12 UTC, dmitrysadovskii requested changes
Переделать задания в соответсвии с оставленными комментариями.

2021-12-26 17:12 UTC, dmitrysadovskii commented on veronika_ivashko/hw_3/task_3_2.py
> +result = some_word + postfix
Если в some_word = "My name Veronika" то данное решение работать не будет.

2021-12-26 17:12 UTC, dmitrysadovskii commented on veronika_ivashko/hw_3/task_3_4.py
> +first_symbol = some_string[0].replace(' ', '')
Если будет 3 пробела в начале и 3 в конце, то данное решение работать не будет.

2021-12-26 18:41 UTC, nik-ar commented on veronika_ivashko/hw_3/task_3_2.py
> +result = some_word + postfix
changed logic in result variable, so postfix is added to each word, and the whole string is reassembled

2021-12-26 18:42 UTC, nik-ar commented on veronika_ivashko/hw_3/task_3_4.py
> +first_symbol = some_string[0].replace(' ', '')
replaced all the logic with strip(), for removing all leading and following white spaces

2021-12-26 18:43 UTC, nik-ar commented
resolved comments

2021-12-27 08:27 UTC, dmitrysadovskii approved these changes

2021-12-27 08:27 UTC, dmitrysadovskii commented on veronika_ivashko/hw_3/task_3_2.py
> +result = ' '.join([word + postfix for word in some_words.split()])
Зачем Тебе цикл for здесь?
метод split разделит слова в список, который передастся в join и преобразует обратно в строку. Нужно лишь указать как join должен обратно преобразовать в строку.
some_words = 'test some more'
"ing ".join(some_words.split())

2021-12-27 08:28 UTC, merged