Homework2 Vadim Shmelev
dmitrysadovskii/tms05_onl pull request #18
Opened 2021-12-26 17:28 UTC by shmelevV

2021-12-26 18:18 UTC, dmitrysadovskii commented
У Тебя подключён CircleCI?

2021-12-26 18:47 UTC, shmelevV commented
Подключен

2021-12-27 08:21 UTC, dmitrysadovskii commented
Почему Ты решил, что circleCi подключен к репозиторию?

2021-12-28 14:13 UTC, dmitrysadovskii commented
CircleCI подключён, теперь нужно избавиться от 3 домашки в PR для 2)

2021-12-28 14:17 UTC, dmitrysadovskii requested changes
Не должно быть 3 домашку а PR для 2

2022-01-11 09:38 UTC, closed without merging