Homework3: Anastasiya Matysheva
dmitrysadovskii/tms05_onl pull request #27
Opened 2021-12-28 21:10 UTC by AnastasiyaMava

2021-12-29 13:32 UTC, dmitrysadovskii requested changes
CircleCI не пройден.
Нет 4 задания.

2021-12-29 20:25 UTC, AnastasiyaMava commented
4 задание добавлено

2021-12-30 22:11 UTC, dmitrysadovskii requested changes
Необходимо исправить комменты

2021-12-30 22:11 UTC, dmitrysadovskii commented on anastasiya_matysheva/hm_3/task_3_2.py
> +End = Worlds + 'ing'
Если в worlds будет "Hi man", то не сработает данное решение

2022-01-04 16:25 UTC, AnastasiyaMava commented on anastasiya_matysheva/hm_3/task_3_2.py
> +End = Worlds + 'ing'
Задание изменила

2022-01-07 08:29 UTC, merged