HomeWork 5: Vladislav Medvedev
dmitrysadovskii/tms05_onl pull request #42
Opened 2022-01-07 22:41 UTC by vladm201098

2022-01-09 11:47 UTC, dmitrysadovskii requested changes

2022-01-09 11:47 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_5/task_5_1.py
> +    input_1 = ''
Зачем нужна эта переменная?

2022-01-09 11:47 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_5/task_5_1.py
> +'''
1. Нет ограничения по символам.
![image](https://user-images.githubusercontent.com/48434081/148680820-5bd97b30-1681-489e-a704-2f12b64af34b.png)
2. При вводе пустой строки выкидывает ошибку
![image](https://user-images.githubusercontent.com/48434081/148680838-b3885345-5567-451e-982f-7953588143a6.png)

2022-01-09 11:47 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_5/task_5_1.py
> +    input_1 = input('Введите 4х значное число: ')
Давай более осмысленные названия переменным.
Например, не input_1, а user_input.

2022-01-09 18:38 UTC, vladm201098 commented on vladslav_medvedev/hm_5/task_5_1.py
> +'''
Исправил !

2022-01-09 18:39 UTC, vladm201098 commented on vladslav_medvedev/hm_5/task_5_1.py
> +    input_1 = input('Введите 4х значное число: ')
Хорошо ,учту , спасибо, уже исправил !

2022-01-09 18:40 UTC, vladm201098 commented on vladslav_medvedev/hm_5/task_5_1.py
> +    input_1 = ''
Cогласен, исправил .

2022-01-11 09:47 UTC, dmitrysadovskii commented
Во втором задании необходимо, что бы язык ответа определялся по букве, которую ввел пользователь. Если это буква англ алфавита, значит язык ответа англ, если русская буква, то русский ответ.

Остальное ок. Исправишь это и можно мержить.

2022-01-12 08:43 UTC, dmitrysadovskii requested changes

2022-01-12 08:43 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_5/task_5_1.py
> +        if count_user_input > 0 or count_user_input < 4\
Можно было записать одним условием: 0 < count_user_input < 4.

2022-01-12 08:43 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_5/task_5_1.py
> +                or count_user_input != '' or not count_user_input.isdigit():
Лучше разделять проверки на пустую строку и на то, что были введены не числа, что бы более точно давать ответ пользователю что именно он сделал не так.
Так как  сообщение "Значение введено неверно!" не очень информативно и не дает понять, что было сделано не так.

2022-01-12 08:43 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_5/task_5_2.py
> +    if 0 < choice and choice < 3:
Можно было одним условием записать: 0 < choice < 3

2022-01-12 08:43 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_5/task_5_2.py
> +    array = choices
Передавай choices в функцию как аргумент.

2022-01-12 08:43 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_5/task_5_2.py
> +    array = choices
Передавай choices в функцию как аргумент.

2022-01-12 08:43 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_5/task_5_2.py
> +        break
Ты проверяешь только по первому символу, поэтому зачем Тебе здесь цикл for? Возьми первый элемент строки list_eng и проверяй по нему.

2022-01-12 09:42 UTC, vladm201098 commented on vladslav_medvedev/hm_5/task_5_2.py
> +        break
Но ведь при первой проверке алфавита ,этой буквы может не оказаться в введеной строке и тогда ему надо будет опять проверять, а букву в алфавите он точно найдет.

2022-01-12 09:42 UTC, vladm201098 commented on vladslav_medvedev/hm_5/task_5_1.py
> +        if count_user_input > 0 or count_user_input < 4\
Понял , спасибо)

2022-01-12 09:42 UTC, vladm201098 commented on vladslav_medvedev/hm_5/task_5_1.py
> +                or count_user_input != '' or not count_user_input.isdigit():
Да - да , я уже понял , мы в прошлый раз это обсудили , но код был написан раньше)

2022-01-12 09:42 UTC, vladm201098 commented on vladslav_medvedev/hm_5/task_5_2.py
> +    if 0 < choice and choice < 3:
Понял ,учту , спасибо

2022-01-12 09:43 UTC, vladm201098 commented on vladslav_medvedev/hm_5/task_5_2.py
> +    array = choices
Исправил!

2022-01-12 09:43 UTC, vladm201098 commented on vladslav_medvedev/hm_5/task_5_2.py
> +    array = choices
Исправил!

2022-01-15 15:13 UTC, merged