Homework5: Vadim Shmelev
dmitrysadovskii/tms05_onl pull request #43
Opened 2022-01-08 16:12 UTC by shmelevV

2022-01-09 11:52 UTC, dmitrysadovskii requested changes

2022-01-09 11:52 UTC, dmitrysadovskii commented on vadim_shmelev/hm5/task_5_1.py
> +from random import choice
1. Нет ограничения на длину строки.
![image](https://user-images.githubusercontent.com/48434081/148680964-b88d25ec-5301-4dce-b44e-d33b5bd51043.png)
2. При вводе пустой стркои выбрасывается исколючение.
![image](https://user-images.githubusercontent.com/48434081/148680978-46644955-b26d-467f-9aa2-24449b79331d.png)

2022-01-09 11:52 UTC, dmitrysadovskii commented on vadim_shmelev/hm5/task_5_1.py
> +x = choice(a)
Давай осмысленные название переменным.
Например, не x, a hidden_number.

2022-01-09 11:52 UTC, dmitrysadovskii commented on vadim_shmelev/hm5/task_5_3.py
> +    elif i % 15 == 0:
Вместо 15 у Тебя будет Fuzz,  а не FuzzBuzz, потому что сработает if
![image](https://user-images.githubusercontent.com/48434081/148681052-b2798634-d983-4be8-a46a-0f6481909dca.png)

2022-01-09 13:18 UTC, shmelevV commented on vadim_shmelev/hm5/task_5_1.py
> +from random import choice
Как предохраниться от пустой строки? Остальное понимаю как исправить.

2022-01-11 09:49 UTC, dmitrysadovskii commented on vadim_shmelev/hm5/task_5_1.py
> +a = '1234567890'
Везде хорошо назвал переменные, но это почему решил обделить Своим вниманием))

2022-01-11 09:49 UTC, dmitrysadovskii commented on vadim_shmelev/hm5/task_5_1.py
> +    y = input('enter 4-digit number:')
Не, еще одну обделенную подруга нашел)

2022-01-11 09:50 UTC, dmitrysadovskii commented
Ок, можно мержить)

2022-01-11 09:50 UTC, merged