homework5 : Valeria Agrest
dmitrysadovskii/tms05_onl pull request #45
Opened 2022-01-09 18:07 UTC by agrestvaleria

2022-01-09 21:27 UTC, dmitrysadovskii requested changes

2022-01-09 21:27 UTC, dmitrysadovskii commented on valeria_agrest/hm_5/task_5_1.py
> +        print('Цыфры не должны повторяться!')
Добавь проверку, на то что должны быть введы цифры
![image](https://user-images.githubusercontent.com/48434081/148701568-0bddd7e4-0ffa-409b-9c9e-7928c50830a8.png)

2022-01-09 21:27 UTC, dmitrysadovskii commented on valeria_agrest/hm_5/tasl_5_3.py
> +        if i % 5 == 0:
Объедени в один if при помощи оператора and

2022-01-11 18:16 UTC, agrestvaleria commented on valeria_agrest/hm_5/task_5_1.py
> +        print('Цыфры не должны повторяться!')
Добавила

2022-01-11 18:17 UTC, agrestvaleria commented on valeria_agrest/hm_5/tasl_5_3.py
> +        if i % 5 == 0:
Объединила

2022-01-12 08:44 UTC, merged