Homework6: Anna Tereshchenko
dmitrysadovskii/tms05_onl pull request #49
Opened 2022-01-09 21:04 UTC by annietereshchenko

2022-01-09 21:52 UTC, dmitrysadovskii requested changes

2022-01-09 21:52 UTC, dmitrysadovskii commented on anna_tereshchenko/hw_6/task_6_1.py
> +while True:
Бесконечные циклы лучше не использовать при написании скриптов, только если в этом есть прямая необходимость. Здесь же можно ввести карту и проверить на валидность, нет необходимости завершать программу только в том случае, если введенная карта была валидна.

2022-01-09 21:52 UTC, dmitrysadovskii commented on anna_tereshchenko/hw_6/task_6_1.py
> +        int_card_number = int(card_number_input)
Зачем Тебе данная переменная?

2022-01-09 21:52 UTC, dmitrysadovskii commented on anna_tereshchenko/hw_6/task_6_1.py
> +def luna_algorithm(card_number):
Не для всех карт работает.
![image](https://user-images.githubusercontent.com/48434081/148702266-7c59dad7-eb4a-4c86-8a16-0a7303fdc5eb.png)

2022-01-09 21:52 UTC, dmitrysadovskii commented on anna_tereshchenko/hw_6/task_6_2.py
> +print(count('abcdddeeeaaa'))
Необходимо подсчитать количество букв в строке. То есть 'abcdddeeeaaa' => "a4bcd3e3"
![image](https://user-images.githubusercontent.com/48434081/148702320-555321ef-08ff-4cbf-98c0-d88905825fb0.png)

2022-01-09 21:52 UTC, dmitrysadovskii commented on anna_tereshchenko/hw_6/task_6_3.py
> +            raise IncorrectValue
В данном случае в этой в кастомной ошибке нету смысла, потому что она вызывается один раз и никакой обработки внутри себя не несет. Можно вывести сообщение о том что не правильное число и сделать continua. Не усложняй код, там где в этом нет необходимости. На небольших задачах это еще не так заметно, но на болших проектах код становится сложно читаемым и менее гибким.

2022-01-09 22:32 UTC, annietereshchenko commented on anna_tereshchenko/hw_6/task_6_1.py
> +while True:
Программа завершается после однократной проверки, даже если карта оказалась не валидной
Пожалуйста, запустите и проверьте еще раз

2022-01-09 22:33 UTC, annietereshchenko commented on anna_tereshchenko/hw_6/task_6_1.py
> +        int_card_number = int(card_number_input)
Переменная int_card_number нужна для того, чтобы убедиться, что введенная строка может быть приведена к числу
Если она не может быть приведена к инту, то пользователь увидит сообщение об ошибке и у него будет возможность ввести число еще раз

2022-01-09 22:35 UTC, annietereshchenko commented on anna_tereshchenko/hw_6/task_6_2.py
> +print(count('abcdddeeeaaa'))
Пример из задания:
"abeehhhhhccced" == "ab**e**2h5c3**e**d"

2022-01-09 23:04 UTC, annietereshchenko commented on anna_tereshchenko/hw_6/task_6_3.py
> +            raise IncorrectValue
Согласна, изменю, спасибо

2022-01-10 08:43 UTC, annietereshchenko commented on anna_tereshchenko/hw_6/task_6_1.py
> +def luna_algorithm(card_number):
Подскажи, пожалуйста, в чем причина? Я склоняюсь к тому, что эта карта действительно невалидна по алгоритму Луна.
Я проверила несколько онлайн калькуляторов + я скопировала код из википедии на python + нашла еще несколько готовых решений в интернете, и все они показывают, что карта невалидна  :(

2022-01-10 18:53 UTC, dmitrysadovskii commented on anna_tereshchenko/hw_6/task_6_1.py
> +def luna_algorithm(card_number):
Да, карта является невалидной, поэтому данный комментарий не актуален.

2022-01-10 18:54 UTC, dmitrysadovskii commented on anna_tereshchenko/hw_6/task_6_2.py
> +print(count('abcdddeeeaaa'))
Заработался. Решение верное.

2022-01-12 08:52 UTC, dmitrysadovskii requested changes

2022-01-12 08:52 UTC, dmitrysadovskii commented on anna_tereshchenko/hw_6/task_6_1.py
> +    s = []
Зачем данный список?

2022-01-12 08:52 UTC, dmitrysadovskii commented on anna_tereshchenko/hw_6/task_6_3.py
> +        if option < 1 or option > 4:
Данную проверку можно свести к одному условию  if not 1 <= option <= 4

2022-01-12 09:18 UTC, annietereshchenko commented on anna_tereshchenko/hw_6/task_6_3.py
> +        if option < 1 or option > 4:
Точно, спасибо!

2022-01-12 09:19 UTC, annietereshchenko commented on anna_tereshchenko/hw_6/task_6_1.py
> +    s = []
Да, совсем не нужен, спасибо

2022-01-15 15:17 UTC, merged