Homework5: Natallia Kodz
dmitrysadovskii/tms05_onl pull request #50
Opened 2022-01-09 21:55 UTC by kodznata

2022-01-11 10:25 UTC, dmitrysadovskii requested changes

2022-01-11 10:25 UTC, dmitrysadovskii commented on natallia_kodz/hm_5/task_5_1.py
> +number1 = 1945
Пользователь не должен иметь возможность вводить повторяющиеся цифры
![image](https://user-images.githubusercontent.com/48434081/148921796-c1528244-59ec-46fd-9718-45faef20645a.png)

2022-01-11 10:25 UTC, dmitrysadovskii commented on natallia_kodz/hm_5/task_5_1.py
> +def function1():
Давай более осмысленные названия. Данная функция возвращает введенные пользователем число, поэтому функцию можно назвать get_valid_user_input()

2022-01-11 10:25 UTC, dmitrysadovskii commented on natallia_kodz/hm_5/task_5_1.py
> +    for i in range(4):
В данном случае 4 является магическим числом и не понятно почему именно 4 здесь, поэтому создай переменную и дай ей коректное название и назначь ей значение 4

2022-01-12 09:03 UTC, dmitrysadovskii requested changes

2022-01-12 09:03 UTC, dmitrysadovskii commented on natallia_kodz/hm_5/task_5_1.py
> +    new_list = list(str(number))
Зачем Ты переменную number приводишь к str, если там и так str и зачем Тебе переменная new_list?

2022-01-12 09:03 UTC, dmitrysadovskii commented on natallia_kodz/hm_5/task_5_1.py
> +    new_list2 = list(str(num2))
Зачем Ты приводишь num2 к list?

2022-01-12 16:47 UTC, kodznata commented on natallia_kodz/hm_5/task_5_1.py
> +    new_list = list(str(number))
Исправила

2022-01-12 16:50 UTC, kodznata commented on natallia_kodz/hm_5/task_5_1.py
> +    new_list2 = list(str(num2))
Дальше в коде я работаю со списками, мне так понятнее, что я делаю

![image](https://user-images.githubusercontent.com/96587299/149184725-5265956f-8f4f-4ca5-b54c-705980ab35fc.png)

2022-01-12 16:51 UTC, kodznata commented on natallia_kodz/hm_5/task_5_1.py
> +def function1():
исправила

2022-01-12 16:52 UTC, kodznata commented on natallia_kodz/hm_5/task_5_1.py
> +    for i in range(4):
исправила

2022-01-15 15:18 UTC, merged