Adding HW5 files
dmitrysadovskii/tms05_onl pull request #55
Opened 2022-01-12 10:07 UTC by nickitque

3 new files with homework5

2022-01-15 15:34 UTC, dmitrysadovskii requested changes

2022-01-15 15:34 UTC, dmitrysadovskii commented on nikita_radzisheuski/hm_5/task_5_1.py
> +"""HOMEWORK TASK NUMBER ONE
Пользователь не должен иметь возможности вводить числа с повторяющимися цифрами.
Можешь не заморачиваться и число, которое нужно отгадать прописать в переменной руками.
![image](https://user-images.githubusercontent.com/48434081/149627389-d7d0e2e0-09b5-4a0c-88fa-43c596b24ece.png)
 
 Нет проверки на длину вводимого числа.
 
![image](https://user-images.githubusercontent.com/48434081/149627452-6223e937-41fc-4f3b-a37b-ac8178e1fc48.png)

Нет проверки на то, что было введено число.
![image](https://user-images.githubusercontent.com/48434081/149627481-5567430d-b827-48d6-bb7b-9381329522eb.png)

2022-01-15 15:34 UTC, dmitrysadovskii commented on nikita_radzisheuski/hm_5/task_5_3.py
> +"""HOMEWORK TASK NUMBER THREE
Вместо 15 отображается Fuzz, а не FuzzBuzz
![image](https://user-images.githubusercontent.com/48434081/149627548-76a3c7a0-9128-4be8-93aa-a2b0f05139b3.png)

2022-01-18 18:53 UTC, nickitque commented on nikita_radzisheuski/hm_5/task_5_3.py
> +"""HOMEWORK TASK NUMBER THREE
@dmitrysadovskii  Привет. Сделал все необходимые изменения:

1. Проверку ввода повторяющихся цифр
2. Проверку длины
3. Проверку ввода числа
4. Пофиксил FuzzBuzz

2022-01-24 10:14 UTC, merged