Homework6: Natallia Kodz
dmitrysadovskii/tms05_onl pull request #56
Opened 2022-01-12 20:14 UTC by kodznata

2022-01-15 15:58 UTC, dmitrysadovskii requested changes

2022-01-15 15:58 UTC, dmitrysadovskii commented on natallia_kodz/hm_6/task_6_1.py
> +    elif set(str(card_number)) <= set('0123456789'):
Почему здесь set? set('0123456789')

2022-01-15 15:58 UTC, dmitrysadovskii commented on natallia_kodz/hm_6/task_6_2.py
> +def letters_count(word):
Неверно работает алгоритм. Должно быть k3ertg2k
![image](https://user-images.githubusercontent.com/48434081/149628426-e66a88a5-b3e2-481f-b945-79b418db2434.png)

2022-01-15 15:58 UTC, dmitrysadovskii commented on natallia_kodz/hm_6/task_6_3.py
> +def calculator(act, num1, num2):
Нет проверки на то, что пользователь ввел число.
![image](https://user-images.githubusercontent.com/48434081/149628512-96fd84ab-d0e7-45c8-9748-912fa226e531.png)

2022-01-18 19:30 UTC, kodznata commented on natallia_kodz/hm_6/task_6_1.py
> +    elif set(str(card_number)) <= set('0123456789'):
я так проверяла, чтобы в введенном номере были только цифры 0,1,2,3,4,5,6,7,8,9 и ничего более

2022-01-18 19:44 UTC, kodznata commented on natallia_kodz/hm_6/task_6_2.py
> +def letters_count(word):
исправила

2022-01-18 19:45 UTC, kodznata commented on natallia_kodz/hm_6/task_6_3.py
> +def calculator(act, num1, num2):
добавила

2022-01-24 10:17 UTC, merged