Homework6: Anastasiya Matysheva
dmitrysadovskii/tms05_onl pull request #58
Opened 2022-01-13 13:11 UTC by AnastasiyaMava

2022-01-16 08:33 UTC, dmitrysadovskii requested changes

2022-01-16 08:33 UTC, dmitrysadovskii commented on anastasiya_matysheva/hm_6/task_6_1.py
> +    code = reduce(str.__add__, filter(str.isdigit, code))
Почему Ты использовала здесь str.__add__?

2022-01-16 08:33 UTC, dmitrysadovskii commented on anastasiya_matysheva/hm_6/task_6_1.py
> +if opt.search(card_numb):
Вынеси проверки в функцию

2022-01-16 08:33 UTC, dmitrysadovskii commented on anastasiya_matysheva/hm_6/task_6_2.py
> +string = input("Write string : ")
Так же необходимо выполнить задание через функцию

2022-01-17 20:19 UTC, AnastasiyaMava commented on anastasiya_matysheva/hm_6/task_6_1.py
> +    code = reduce(str.__add__, filter(str.isdigit, code))
Нужно сложить символы в строчку было, __add__ подходит - оператор сложения. reduce вызовет add для всего отфильтрованного списка

2022-01-24 10:22 UTC, dmitrysadovskii commented
7 домашка не должна быть в PR для 6 домашки.
Так все ок. Убери 7 домашку с ПР и можно мержить.

2022-02-07 02:36 UTC, merged