Homework 6: Vladislav Medvedev
dmitrysadovskii/tms05_onl pull request #62
Opened 2022-01-13 21:53 UTC by vladm201098

2022-01-16 08:45 UTC, dmitrysadovskii commented
Влад, у Тебя и 5 и 6 домашка тут. Разберись какая нужна и оставь ее для проверки.

2022-01-16 08:45 UTC, dmitrysadovskii requested changes

2022-01-16 08:45 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_5/task_5_1.py
> +    input_1 = ''
Зачем эта переменная?

2022-01-16 08:45 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_5/task_5_1.py
> +'''
Пользователь не должен иметь возможности вводить одинаковые цифры в числе и вводить буквы.
![image](https://user-images.githubusercontent.com/48434081/149653072-c28af9d8-6e4e-4ce9-8978-a598ef889f02.png)


При вводе пустой строки программа падает
![image](https://user-images.githubusercontent.com/48434081/149653099-1880b912-ab1b-43cd-a68d-74cf381ff350.png)

Пользователь может вводить числа больше 4 цифр.
Программа не корректно считает коров.
![image](https://user-images.githubusercontent.com/48434081/149653158-66eaabbf-9336-4335-b1cb-083a2780080e.png)

2022-01-16 08:45 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_5/task_5_2.py
> +    if 0 < choice and choice < 3:
Можно объединить в одно условие 0 < choice < 3:

2022-01-16 08:45 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_5/task_5_2.py
> +inp = input("Choise a language: 1-English or 2-Russian: ")
Определение языка должно происходит автоматически по первой введенной букве.

2022-01-16 11:54 UTC, vladm201098 commented
> Влад, у Тебя и 5 и 6 домашка тут. Разберись какая нужна и оставь ее для проверки.

Все исправил !

2022-01-16 11:55 UTC, vladm201098 commented
> Влад, у Тебя и 5 и 6 домашка тут. Разберись какая нужна и оставь ее для проверки.

Исправил

2022-01-24 10:26 UTC, dmitrysadovskii commented
Все ок, только сперва необходимо зарезолвить конфликты

2022-01-24 18:54 UTC, vladm201098 commented on vladslav_medvedev/hm_5/task_5_1.py
> +    input_1 = ''
Исправил

2022-01-24 18:54 UTC, vladm201098 commented on vladslav_medvedev/hm_5/task_5_1.py
> +'''
Исправлено в пред таске!

2022-01-24 18:55 UTC, vladm201098 commented on vladslav_medvedev/hm_5/task_5_2.py
> +    if 0 < choice and choice < 3:
Понял , учту

2022-01-24 18:55 UTC, vladm201098 commented on vladslav_medvedev/hm_5/task_5_2.py
> +inp = input("Choise a language: 1-English or 2-Russian: ")
Исправил

2022-01-26 19:58 UTC, closed without merging