homework7 : Valeria Agrest
dmitrysadovskii/tms05_onl pull request #66
Opened 2022-01-16 15:11 UTC by agrestvaleria

2022-01-16 18:58 UTC, dmitrysadovskii requested changes

2022-01-16 18:58 UTC, dmitrysadovskii commented on valeria_agrest/hm_7/task_7_1.py
> +            i += 1
Почему здесь делаешь i += 1, если дальше по коду делаешь return в цикле?

2022-01-16 18:58 UTC, dmitrysadovskii commented on valeria_agrest/hm_7/task_7_2.py
> +        print(result)
Логика в encode и decode отличается тем, что в первом случае Ты складываешь, во втором вычитаешь. В остальном логика повторяется. Вынеси данную логику в функцию, где аргументом будешь принимать тип действия (encode/decode)
Тогда перед определением переменной new_position будешь проверять у Нас сейчас режим encode или decode и в зависимости от этого будет складывать или вычитать.

2022-01-16 18:58 UTC, dmitrysadovskii commented on valeria_agrest/hm_7/task_7_2.py
> +            if i in alphabet_en:
Что бы не писать отдельно if на англ, потом на русский, можно сделать следующее.
Перед if задать переменную alphabet_lang = alphabet_ru
И далее в if проверять, принадлежит ли буква англ алфавиту. Если да, то в if менять переменную alphabet_lang на англ алфавит. Это Тебя избавит от ненужного if/elif и уменьшит дубликацию кода.

2022-01-19 20:35 UTC, agrestvaleria commented on valeria_agrest/hm_7/task_7_1.py
> +            i += 1
Удалила i += 1 вообще

2022-01-19 20:35 UTC, agrestvaleria commented on valeria_agrest/hm_7/task_7_2.py
> +        print(result)
Сделала

2022-01-19 20:35 UTC, agrestvaleria commented on valeria_agrest/hm_7/task_7_2.py
> +            if i in alphabet_en:
Сделала

2022-01-24 10:29 UTC, merged