Homework7: Natallia Kodz
dmitrysadovskii/tms05_onl pull request #71
Opened 2022-01-18 22:33 UTC by kodznata

2022-01-24 10:59 UTC, dmitrysadovskii commented
Исправь коммент и можно мержить.

2022-01-24 10:59 UTC, dmitrysadovskii requested changes

2022-01-24 10:59 UTC, dmitrysadovskii commented on natallia_kodz/hm_7/task_7_1.py
> +    else:
else не имеет смысла здесь, так как если if будет False, то в любом случае перейдет к последнему return

2022-01-24 17:54 UTC, kodznata commented on natallia_kodz/hm_7/task_7_1.py
> +    else:
Не очень поняла, что мне нужно исправить. У меня 2 разных результата: если if выполняется, то возвращается матрица, в противном случае программа идет по ветке else и возвращает мне сообщение

2022-01-24 17:56 UTC, kodznata commented on natallia_kodz/hm_7/task_7_1.py
> +    else:
![image](https://user-images.githubusercontent.com/96587299/150837696-ad09bd70-a167-456c-8cc5-63f4606af622.png)
![image](https://user-images.githubusercontent.com/96587299/150837859-7b5a4133-8085-40a7-bceb-d5756a9676be.png)

2022-02-07 03:02 UTC, dmitrysadovskii requested changes

2022-02-07 03:02 UTC, dmitrysadovskii commented on natallia_kodz/hm_7/task_7_1.py
> +    else:
У Тебя есть условие if/ else. Если условие в if будет верным, то вернется result_list. Если условие в if будет не верным, то программа перейдет в ветку else и вернет сообщение. 
Что будет, если у Нас будет только условие if?
Если условие в if будет не верным, то нам вернется сообщение об ошибке из-за чего можно сделать вывод, что else здесь избыточен и не несет в себе никакой смысловой нагрузки. 
if (condition):
    ...
    return result_list
return "error message"

2022-02-07 03:02 UTC, dmitrysadovskii commented on natallia_kodz/hm_7/task_7_1.py
> +    else:
В данносм случае даже лучше было бы сделать assert перед тем как работать в цикле с данными значениями.
assert len(initial_list) == rows_num * elements_num, "Initial number of elements can't be transformed into requested matrix"
for i in range(rows_num):
    ....
return result_list

Так Ты сможешь проверить, что значения которые были переданны валидны и приступила бы к работе с ними в цикле for. В противном же случае у Тебя выдалась бы ошибка.

2022-02-17 16:51 UTC, kodznata commented on natallia_kodz/hm_7/task_7_1.py
> +    else:
Спасибо, я поняла. Мне почему-то казалось, что без else у меня не будет перехода на error message при невыполнении условия. И еще я как-то упустила, что при выполнении условия код стопнется на первом return и не пойдет потом отображать следующий return без else.  В общем, картинка сложилась ))

2022-02-18 05:59 UTC, merged