Homework 8: Vladislav Medvedev
dmitrysadovskii/tms05_onl pull request #80
Opened 2022-01-22 15:35 UTC by vladm201098

2022-01-24 11:58 UTC, dmitrysadovskii requested changes
Меня только один коммент смущает, остальное все ок. Можно будет мержить.

2022-01-24 11:58 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_8/task_8_2.py
> +    if __name__ == '__main__':
Зачем данный if?

2022-01-25 22:19 UTC, vladm201098 commented on vladslav_medvedev/hm_8/task_8_2.py
> +    if __name__ == '__main__':
Честно говоря такую конструкцию нашел в интернете , не совсем понял принцип ее работы , но это заработало!! :D

2022-02-10 03:14 UTC, dmitrysadovskii requested changes

2022-02-10 03:14 UTC, dmitrysadovskii commented on vladslav_medvedev/hm_8/task_8_2.py
> +    if __name__ == '__main__':
Какая была за ошибка?
Проверил, без if тоже работает.

2022-02-12 18:54 UTC, vladm201098 commented on vladslav_medvedev/hm_8/task_8_2.py
> +    if __name__ == '__main__':
Исправил!

2022-02-18 06:10 UTC, merged