Homework9: Veronika Ivashko
dmitrysadovskii/tms05_onl pull request #83
Opened 2022-01-23 15:15 UTC by nik-ar

added files for ninth homework

2022-01-24 12:07 UTC, dmitrysadovskii requested changes

2022-01-24 12:07 UTC, dmitrysadovskii commented on veronika_ivashko/hw_9/task_9_1.py
> +                 is_reserved=0, is_taken=0):
Лучше is_reserved указывать как True/False. Не стоит усложнять и запутывать себе жизнь)

2022-01-24 12:07 UTC, dmitrysadovskii commented on veronika_ivashko/hw_9/task_9_1.py
> +    def __init__(self, name: str, id_number=total_visitors + 1):
лучше вынести из аргументов __init__, так как при инициализации экземпляра класса Visitor можно узакать id_number

2022-01-24 12:07 UTC, dmitrysadovskii commented on veronika_ivashko/hw_9/task_9_1.py
> +        if book.is_reserved == 0 and book.is_taken == 0:
0 в питоне является False объектом, поэтому можно указать not book.is_reserved.
Лучше было бы if разбить на две проверки: 
- В первой проверяешь что книга не зарезервирована
- Во второй проверяешб что книга не взята

в зависимости от того какой if сработает укажаешь в принте какое состояние у книги зарезервирована/взята. Так пользователю будет более точно знать о текущем состоянии книги, а не догатывать что с ней не так + избавишься от ненужного else.

2022-01-24 12:07 UTC, dmitrysadovskii commented on veronika_ivashko/hw_9/task_9_1.py
> +                and (book.is_reserved == 1 or book.is_taken == 1):
Создай даже метод is_book_available и там проверяй свободна ли книга.

2022-01-24 19:28 UTC, nik-ar commented on veronika_ivashko/hw_9/task_9_1.py
> +                 is_reserved=0, is_taken=0):
fixed

2022-01-24 19:29 UTC, nik-ar commented on veronika_ivashko/hw_9/task_9_1.py
> +    def __init__(self, name: str, id_number=total_visitors + 1):
fixed, 
вынесла из init и скрыла этот атрибут

2022-01-24 19:30 UTC, nik-ar commented on veronika_ivashko/hw_9/task_9_1.py
> +        if book.is_reserved == 0 and book.is_taken == 0:
fixed

2022-01-24 19:30 UTC, nik-ar commented on veronika_ivashko/hw_9/task_9_1.py
> +                and (book.is_reserved == 1 or book.is_taken == 1):
added

2022-01-24 19:35 UTC, nik-ar commented
added fixes, resolved comments

2022-02-10 03:02 UTC, dmitrysadovskii approved these changes

2022-02-10 03:02 UTC, merged