Homework9: Valeria Agrest
dmitrysadovskii/tms05_onl pull request #84
Opened 2022-01-23 19:36 UTC by agrestvaleria

2022-01-24 12:09 UTC, dmitrysadovskii requested changes

2022-01-24 12:09 UTC, dmitrysadovskii commented on valeria_agrest/hm_9/task_9_1.py
> +            if a_book.taken == 0 and a_book.reserved == 0:
Почему a_book.taken проверяешь на 0?

2022-01-24 12:14 UTC, dmitrysadovskii requested changes

2022-01-24 12:14 UTC, dmitrysadovskii commented on valeria_agrest/hm_9/task_9_1.py
> +        self.isbn = isbn
Пользователь может создать 2 книги с одинаковым isbn

2022-01-24 13:02 UTC, agrestvaleria commented on valeria_agrest/hm_9/task_9_1.py
> +        self.isbn = isbn
Т.е. нужно проверять, ввел ли пользователь уникальный isbn?

2022-01-24 17:30 UTC, agrestvaleria commented on valeria_agrest/hm_9/task_9_1.py
> +            if a_book.taken == 0 and a_book.reserved == 0:
Ммм, кажется, я поняла свой недочет, переделаю. Не понимаю твой второй коммент ниже, жду пояснений :)

2022-01-24 17:33 UTC, agrestvaleria commented on valeria_agrest/hm_9/task_9_1.py
> +            if a_book.taken == 0 and a_book.reserved == 0:
Ммм, кажется, я поняла свой недочет, исправлю. Поясни, пожалуйста, второй коммент, не совсем понимаю, что от меня требуется)

2022-01-26 18:21 UTC, agrestvaleria commented on valeria_agrest/hm_9/task_9_1.py
> +        self.isbn = isbn
Внесла проверку на уникальность

2022-01-26 18:25 UTC, agrestvaleria commented on valeria_agrest/hm_9/task_9_1.py
> +            if a_book.taken == 0 and a_book.reserved == 0:
Исправила

2022-02-10 03:15 UTC, merged