Homework 8: Natallia Kodz
dmitrysadovskii/tms05_onl pull request #86
Opened 2022-01-24 18:41 UTC by kodznata

2022-02-10 12:02 UTC, dmitrysadovskii requested changes
Хорошая работа, волнует только вопрос с exit()

2022-02-10 12:02 UTC, dmitrysadovskii commented on natallia_kodz/hm_8/task_8_2.py
> +            exit()
Почему используешь exit()?

2022-02-10 12:02 UTC, dmitrysadovskii commented on natallia_kodz/hm_8/task_8_1.py
> +                    if isinstance(i, str):
Данное разветвление логики здесь лишнее. Желательно избегать лишних if конструкций, что бы не усложнять логику, так как это потенциально может привести к багам.

2022-02-17 17:11 UTC, kodznata commented on natallia_kodz/hm_8/task_8_2.py
> +            exit()
Я хотела вывести сообщение и стопнуть весь код, если числа не прошли проверки в функции, и нашла только такой способ это сделать. В других вариантах у меня продолжалось выполнение кода декоратора

2022-02-17 17:36 UTC, kodznata commented on natallia_kodz/hm_8/task_8_1.py
> +                    if isinstance(i, str):
Исправила

2022-02-18 06:00 UTC, merged